# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_large_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_many_window(object):
    def setupUi(self, add_many_window):
        add_many_window.setObjectName("add_many_window")
        add_many_window.resize(274, 146)
        self.centralwidget = QtWidgets.QWidget(add_many_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.large_add_box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.large_add_box.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.large_add_box.setObjectName("large_add_box")
        self.verticalLayout.addWidget(self.large_add_box)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_large_words = QtWidgets.QPushButton(self.centralwidget)
        self.add_large_words.setObjectName("add_large_words")
        self.horizontalLayout.addWidget(self.add_large_words)
        self.cancel_large_words = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_large_words.setObjectName("cancel_large_words")
        self.horizontalLayout.addWidget(self.cancel_large_words)
        self.verticalLayout.addLayout(self.horizontalLayout)
        add_many_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(add_many_window)
        QtCore.QMetaObject.connectSlotsByName(add_many_window)

    def retranslateUi(self, add_many_window):
        _translate = QtCore.QCoreApplication.translate
        add_many_window.setWindowTitle(_translate("add_many_window", "Add Text"))
        self.large_add_box.setPlaceholderText(_translate("add_many_window", "Type, drag and drop, or copy and paste text into box."))
        self.add_large_words.setText(_translate("add_many_window", "Add"))
        self.cancel_large_words.setText(_translate("add_many_window", "Cancel"))
