# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remove_word_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_remove_word_window(object):
    def setupUi(self, remove_word_window):
        remove_word_window.setObjectName("remove_word_window")
        remove_word_window.resize(297, 105)
        self.centralwidget = QtWidgets.QWidget(remove_word_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.delete_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_label.setFont(font)
        self.delete_label.setObjectName("delete_label")
        self.verticalLayout.addWidget(self.delete_label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(275, 52))
        self.frame.setMaximumSize(QtCore.QSize(275, 52))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes_del_button = QtWidgets.QPushButton(self.frame)
        self.yes_del_button.setObjectName("yes_del_button")
        self.horizontalLayout.addWidget(self.yes_del_button)
        self.cancel_del_button = QtWidgets.QPushButton(self.frame)
        self.cancel_del_button.setObjectName("cancel_del_button")
        self.horizontalLayout.addWidget(self.cancel_del_button)
        self.verticalLayout.addWidget(self.frame)
        remove_word_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(remove_word_window)
        QtCore.QMetaObject.connectSlotsByName(remove_word_window)

    def retranslateUi(self, remove_word_window):
        _translate = QtCore.QCoreApplication.translate
        remove_word_window.setWindowTitle(_translate("remove_word_window", "Remove Word"))
        self.delete_label.setText(_translate("remove_word_window", "TextLabel"))
        self.yes_del_button.setText(_translate("remove_word_window", "Yes"))
        self.cancel_del_button.setText(_translate("remove_word_window", "Cancel"))
