# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_word_window_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_word_window(object):
    def setupUi(self, add_word_window):
        add_word_window.setObjectName("add_word_window")
        add_word_window.resize(248, 148)
        self.centralwidget = QtWidgets.QWidget(add_word_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_word_line = QtWidgets.QLineEdit(self.centralwidget)
        self.add_word_line.setMinimumSize(QtCore.QSize(50, 50))
        self.add_word_line.setText("")
        self.add_word_line.setObjectName("add_word_line")
        self.verticalLayout.addWidget(self.add_word_line)
        add_word_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(add_word_window)
        self.statusbar.setObjectName("statusbar")
        add_word_window.setStatusBar(self.statusbar)

        self.retranslateUi(add_word_window)
        QtCore.QMetaObject.connectSlotsByName(add_word_window)

    def retranslateUi(self, add_word_window):
        _translate = QtCore.QCoreApplication.translate
        add_word_window.setWindowTitle(_translate("add_word_window", "Add Word"))
        self.add_word_line.setPlaceholderText(_translate("add_word_window", "Type word"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_word_window = QtWidgets.QMainWindow()
    ui = Ui_add_word_window()
    ui.setupUi(add_word_window)
    add_word_window.show()
    sys.exit(app.exec_())
