# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remember_words_gui_template_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 224)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("MainWindow{\n"
"background:\n"
"}\n"
"\n"
"\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_word_button = QtWidgets.QPushButton(self.frame)
        self.add_word_button.setMinimumSize(QtCore.QSize(75, 25))
        self.add_word_button.setStyleSheet("")
        self.add_word_button.setObjectName("add_word_button")
        self.horizontalLayout.addWidget(self.add_word_button)
        self.remove_word_button = QtWidgets.QPushButton(self.frame)
        self.remove_word_button.setMinimumSize(QtCore.QSize(75, 25))
        self.remove_word_button.setObjectName("remove_word_button")
        self.horizontalLayout.addWidget(self.remove_word_button)
        self.search_bar = QtWidgets.QLineEdit(self.frame)
        self.search_bar.setText("")
        self.search_bar.setFrame(False)
        self.search_bar.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout.addWidget(self.search_bar)
        self.verticalLayout.addWidget(self.frame)
        self.word_bank = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_bank.sizePolicy().hasHeightForWidth())
        self.word_bank.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(9)
        self.word_bank.setFont(font)
        self.word_bank.setStyleSheet("QListView{\n"
"background:rgb(245, 242, 235)\n"
"}\n"
"\n"
"")
        self.word_bank.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.word_bank.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.word_bank.setResizeMode(QtWidgets.QListView.Adjust)
        self.word_bank.setObjectName("word_bank")
        self.verticalLayout.addWidget(self.word_bank)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 261, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionDownload_Database = QtWidgets.QAction(MainWindow)
        self.actionDownload_Database.setObjectName("actionDownload_Database")
        self.actionUpload_Database = QtWidgets.QAction(MainWindow)
        self.actionUpload_Database.setObjectName("actionUpload_Database")
        self.actionAdd_Definitions = QtWidgets.QAction(MainWindow)
        self.actionAdd_Definitions.setObjectName("actionAdd_Definitions")
        self.menuOptions.addAction(self.actionSettings)
        self.menuOptions.addAction(self.actionDownload_Database)
        self.menuOptions.addAction(self.actionUpload_Database)
        self.menuOptions.addAction(self.actionAdd_Definitions)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remember Words"))
        self.add_word_button.setText(_translate("MainWindow", "Add"))
        self.remove_word_button.setText(_translate("MainWindow", "Remove"))
        self.search_bar.setPlaceholderText(_translate("MainWindow", "Search"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionDownload_Database.setText(_translate("MainWindow", "Download Database"))
        self.actionUpload_Database.setText(_translate("MainWindow", "Upload Database"))
        self.actionAdd_Definitions.setText(_translate("MainWindow", "Add Definitions"))
